#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 28 21:51:53 CEST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
