name = "sixseven"
author = "monkey52x"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40956e449c0b5e59c0766892ab6fdd9c3142949eeb5e2ddc15c482b804447198"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
